# Generated by Django 3.2.10 on 2021-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupLink', models.TextField()),
                ('contactLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageBannerAds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocalNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
    ]
