# Generated by Django 3.2.10 on 2021-12-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupLink', models.TextField()),
                ('contactLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageBannerAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/advertisement')),
            ],
        ),
    ]
