# Generated by Django 3.2.10 on 2021-12-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_contact_homepagebannerads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='trendingnews',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
