# Generated by Django 3.2.10 on 2021-12-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_entertainmentnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakingnews',
            name='cropping',
        ),
        migrations.AddField(
            model_name='breakingnews',
            name='creator_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breakingnews',
            name='creator_type',
            field=models.CharField(default='ulliyeri news webdesk', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainmentnews',
            name='creator_id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainmentnews',
            name='creator_type',
            field=models.CharField(default='ulliyeri news webdesk', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestnews',
            name='creator_id',
            field=models.CharField(default='badshah', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestnews',
            name='creator_type',
            field=models.CharField(default='ulliyeri news webdesk', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendingnews',
            name='creator_id',
            field=models.CharField(default='bijin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendingnews',
            name='creator_type',
            field=models.CharField(default='ulliyeri news webdesk', max_length=50),
            preserve_default=False,
        ),
    ]
