# Generated by Django 3.2.10 on 2021-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0013_obituary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('recipe_by', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
    ]
