# Generated by Django 3.2.10 on 2021-12-25 18:49

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnews',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1920x1080', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='heading',
            field=models.CharField(max_length=150),
        ),
    ]
