# Generated by Django 3.2.10 on 2021-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0009_auto_20211227_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnews',
            name='short_news',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainmentnews',
            name='short_news',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestnews',
            name='short_news',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendingnews',
            name='short_news',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
