# Generated by Django 3.2.10 on 2021-12-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0011_auto_20211228_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocalNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
    ]
