# Generated by Django 3.2.10 on 2021-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0012_educationnews_localnews_politicalnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=150)),
                ('short_news', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('creator_type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
    ]
